// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISb3K_YO6MSM6XcO_Iwa6zfjcKVX6hMc',
    appId: '1:42382483684:web:feb08764da71c6d6fd4cf1',
    messagingSenderId: '42382483684',
    projectId: 'day1task',
    authDomain: 'day1task.firebaseapp.com',
    storageBucket: 'day1task.firebasestorage.app',
    measurementId: 'G-FWHL4TMR44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltKrq5LjcEsmUqRoP_6FzQ2CH72_bxO4',
    appId: '1:42382483684:android:d9b08132f6f1bf5bfd4cf1',
    messagingSenderId: '42382483684',
    projectId: 'day1task',
    storageBucket: 'day1task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRdTJMIFV75ADd-KauWMqPpRAp4Ryg_w',
    appId: '1:42382483684:ios:c39bfe20f9ce5695fd4cf1',
    messagingSenderId: '42382483684',
    projectId: 'day1task',
    storageBucket: 'day1task.firebasestorage.app',
    iosBundleId: 'com.example.day1task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdRdTJMIFV75ADd-KauWMqPpRAp4Ryg_w',
    appId: '1:42382483684:ios:c39bfe20f9ce5695fd4cf1',
    messagingSenderId: '42382483684',
    projectId: 'day1task',
    storageBucket: 'day1task.firebasestorage.app',
    iosBundleId: 'com.example.day1task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISb3K_YO6MSM6XcO_Iwa6zfjcKVX6hMc',
    appId: '1:42382483684:web:0ee771fe2dcbefc4fd4cf1',
    messagingSenderId: '42382483684',
    projectId: 'day1task',
    authDomain: 'day1task.firebaseapp.com',
    storageBucket: 'day1task.firebasestorage.app',
    measurementId: 'G-KK7BZ0JMVR',
  );
}
